import { useMemo, useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, ArrowRight, Check, ChevronDown, Clock3, Database, FileCheck2, Fingerprint, Gauge, Layers3, Search, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import { duplicatePairs, issues as seedIssues, ledgerEvents, predictions, weeklyMetrics } from '../../data/seed';
import { researchApi, type ModelPrediction, type DuplicateCandidate } from '../../lib/api';
import { categories } from '../../types';
import type { Category, Prediction } from '../../types';
import { Button } from '../../components/shared/Button';
import { MetricCard } from '../../components/shared/MetricCard';
import { PageHeader, Panel } from '../../components/shared/Primitives';
import { StatusBadge } from '../../components/shared/StatusBadge';

const palette=['#4F5B2A','#B8892D','#D8C9A8','#6B7A3A','#2A3320'];
const tip={contentStyle:{backgroundColor:'#2A3320',border:0,borderRadius:0,color:'#fff',fontSize:10},itemStyle:{color:'#fff'}};
const quick=[{title:'Models',desc:'Inspect classification, routing, and proof models.',href:'/research/models',icon:Layers3},{title:'Duplicates',desc:'Compare spatial and semantic match performance.',href:'/research/duplicates',icon:Target},{title:'Proof audit',desc:'Review automated proof plausibility signals.',href:'/research/proof-audit',icon:FileCheck2},{title:'Metrics',desc:'Explore evaluation metrics and data splits.',href:'/research/metrics',icon:Activity},{title:'Audit ledger',desc:'Verify event integrity and trace status changes.',href:'/research/audit-ledger',icon:Fingerprint},{title:'Dataset info',desc:'Synthetic Pune civic dataset · v0.3.',href:'/research/metrics#dataset',icon:Database}];

export function ResearchOverview(){
  const latest=predictions.slice(0,5);
  return <div><PageHeader eyebrow="CivicLens · model inspection and evaluation tools" title="Research dashboard" description="Inspect prediction quality, proof checks, duplication signals, and the integrity of synthetic civic data." action={<span className="border-2 border-[#B8892D] bg-[#B8892D]/10 px-3 py-2 text-[9px] font-black uppercase tracking-widest text-[#B8892D]">Research mode</span>}/>
    <div className="mb-8 grid grid-cols-2 gap-4 xl:grid-cols-4"><MetricCard value="1,247" label="Total predictions" icon={Sparkles} accentColor="olive"/><MetricCard value="0.82" label="Avg. confidence" sublabel="Across active modules" icon={Gauge} accentColor="gold"/><MetricCard value="6" label="Active models" sublabel="M1–M6" icon={Layers3} accentColor="sand"/><MetricCard value="v0.3" label="Dataset version" sublabel="Pune · synthetic" icon={Database} accentColor="olive"/></div>
    <section className="mb-8"><div className="mb-4 border-b-4 border-[#2A3320] pb-3"><p className="eyebrow">Research tools</p><h2 className="display-title mt-1 text-xl">Quick access</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{quick.map(({title,desc,href,icon:Icon},index)=><Link key={title} to={href} className="group border-4 border-[#2A3320] bg-[#FDFBF7] p-5 shadow-[5px_5px_0px_0px_#2A3320] transition-all hover:-translate-y-1"><div className="flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center border-2 border-[#2A3320] ${index%3===0?'bg-[#4F5B2A] text-white':index%3===1?'bg-[#B8892D] text-white':'bg-[#D8C9A8] text-[#2A3320]'}`}><Icon size={18}/></span><ArrowRight size={17} className="transition-transform group-hover:translate-x-1"/></div><h3 className="display-title mt-5 text-base">{title}</h3><p className="mt-2 text-xs leading-relaxed text-[#2A3320]/65">{desc}</p><p className="mt-4 text-[9px] font-black uppercase tracking-widest text-[#4F5B2A]">Open →</p></Link>)}</div></section>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section><div className="mb-3 border-b-4 border-[#2A3320] pb-3"><p className="eyebrow">Latest model activity</p><h2 className="display-title mt-1 text-lg">Recent predictions</h2></div><div className="overflow-x-auto border-4 border-[#2A3320] bg-[#FDFBF7]"><table className="data-table"><thead><tr>{['Issue','Module','Prediction','Confidence','Status'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{latest.map((item,index)=><tr key={`${item.issueId}-${item.module}`}><td className="font-black">{item.issueId}</td><td>{item.module}</td><td className="max-w-52 truncate">{item.prediction}</td><td><ConfidenceBar value={item.confidence}/></td><td><span className="text-[9px] font-black uppercase">{index===2?'⚠':'✓'} {item.status}</span></td></tr>)}</tbody></table></div></section><Panel className="border-4"><p className="eyebrow">System health</p><h2 className="display-title mt-1 text-lg">Evaluation services</h2><div className="mt-4 space-y-4">{[['API latency','p95 420ms'],['Queue depth','3 pending'],['Last snapshot','2 hours ago']].map(([label,value],index)=><div key={label} className="flex items-center justify-between border-b-2 border-[#E8E0D0] pb-3"><span className="flex items-center gap-2 text-xs font-bold"><i className={`h-2 w-2 rounded-full ${index===1?'bg-[#B8892D]':'bg-[#4F5B2A]'}`}/>{label}</span><b className="display-title text-sm">{value}</b></div>)}</div><div className="mt-5 border-2 border-[#4F5B2A] bg-[#4F5B2A]/10 p-3 text-[9px] font-black uppercase tracking-wider">All values are illustrative and synthetic</div></Panel></div></div>;
}
function ConfidenceBar({value}:{value:number}){return <div className="flex min-w-24 items-center gap-2"><div className="h-2 w-16 border border-[#2A3320] bg-[#E8E0D0]"><div className="h-full bg-[#4F5B2A]" style={{width:`${value*100}%`}}/></div><span className="text-[10px] font-bold">{value.toFixed(2)}</span></div>}

export function ModelPredictions(){
  const [module,setModule]=useState('All');const [min,setMin]=useState(.5);const [query,setQuery]=useState('');const [expanded,setExpanded]=useState<string|null>(null);
  const rows=useMemo(()=>predictions.filter(item=>(module==='All'||item.module===module)&&item.confidence>=min&&item.issueId.toLowerCase().includes(query.toLowerCase())),[module,min,query]);
  return <div><PageHeader eyebrow="Evaluation workspace" title="Model predictions" description="Inspect synthetic module outputs, confidence, and editable prediction explanations." action={<span className="border-2 border-[#2A3320] bg-[#D8C9A8] px-3 py-2 text-[10px] font-black uppercase tracking-wider">{rows.length} records</span>}/><div className="mb-5 flex flex-wrap items-end gap-4 border-2 border-[#2A3320] bg-[#FDFBF7] p-4"><div><p className="eyebrow mb-2">Module</p><div className="flex flex-wrap gap-1.5">{['All','M1','M2','M3','M4','M5','M6'].map(value=><button key={value} onClick={()=>setModule(value)} className={`border-2 border-[#2A3320] px-3 py-2 text-[9px] font-black ${module===value?'bg-[#4F5B2A] text-white':'bg-white'}`}>{value}</button>)}</div></div><div className="min-w-40 flex-1"><label className="eyebrow flex justify-between">Minimum confidence <span>{min.toFixed(2)}</span></label><input type="range" min="0" max="1" step="0.05" value={min} onChange={event=>setMin(Number(event.target.value))} className="mt-2 w-full accent-[#4F5B2A]"/></div><label className="flex items-center gap-2 border-2 border-[#2A3320] bg-white px-3 py-2"><Search size={14}/><input aria-label="Filter issue id" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Issue ID" className="w-28 text-xs outline-none"/></label></div>
    <div className="overflow-x-auto border-4 border-[#2A3320] bg-[#FDFBF7]"><table className="data-table"><thead><tr>{['Issue','Module','Prediction','Confidence','Status','Model','Timestamp',''].map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map((item,index)=>{const key=`${item.issueId}-${item.module}-${index}`;return <FragmentRow key={key} item={item} expanded={expanded===key} onClick={()=>setExpanded(expanded===key?null:key)}/>})}</tbody></table></div>{rows.length===0&&<p className="border-x-4 border-b-4 border-[#2A3320] bg-[#FDFBF7] p-6 text-center text-sm">No predictions match the current filters.</p>}</div>;
}
function FragmentRow({item,expanded,onClick}:{item:Prediction;expanded:boolean;onClick:()=>void}){return <><tr onClick={onClick} className="cursor-pointer"><td className="font-black">{item.issueId}</td><td>{item.module}</td><td>{item.prediction}</td><td><ConfidenceBar value={item.confidence}/></td><td><span className={`text-[9px] font-black uppercase ${item.status==='Needs review'?'text-[#B8892D]':'text-[#4F5B2A]'}`}>{item.status==='Needs review'?'⚠':'✓'} {item.status}</span></td><td>{item.model}</td><td>{item.timestamp}</td><td><ChevronDown size={15} className={expanded?'rotate-180':''}/></td></tr>{expanded&&<tr><td colSpan={8} className="bg-[#D8C9A8]/20"><p className="eyebrow">Model explanation</p><p className="mt-1 text-xs leading-relaxed">{item.explanation}</p><p className="mt-2 font-mono text-[9px] text-[#2A3320]/55">{JSON.stringify({module:item.module,prediction:item.prediction,confidence:item.confidence,model:item.model})}</p><Link to={`/transparency/issue/${item.issueId}`} className="mt-2 inline-block text-[9px] font-black uppercase text-[#4F5B2A] underline">Input reference · {item.issueId} ↗</Link></td></tr>}</>}

export function DuplicateAnalysis(){
  const performance=[{metric:'Precision',distance:0.72,text:0.77,combined:0.88},{metric:'Recall',distance:0.68,text:0.74,combined:0.83},{metric:'F1',distance:0.70,text:0.75,combined:0.85}];const outcome=[{name:'Confirmed',value:1},{name:'Rejected',value:1},{name:'Pending',value:2}];
  return <div><PageHeader eyebrow="Evaluation workspace · M3" title="Duplicate detection analysis" description="Compare candidate pairs and review the combined spatial and semantic model against baselines."/><div className="mb-7 overflow-x-auto border-4 border-[#2A3320] bg-[#FDFBF7]"><table className="data-table"><thead><tr>{['Issue A','Issue B','Spatial distance','Text similarity','Category match','Overall score','Outcome'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{duplicatePairs.map(pair=><tr key={`${pair.issueA}-${pair.issueB}`}><td className="font-black">{pair.issueA}</td><td className="font-black">{pair.issueB}</td><td>{pair.distance}m</td><td>{pair.textSimilarity.toFixed(2)}</td><td>{pair.categoryMatch?'✓ match':'—'}</td><td className="font-black">{pair.score.toFixed(2)}</td><td><span className={`text-[9px] font-black uppercase ${pair.outcome==='Confirmed'?'text-[#4F5B2A]':pair.outcome==='Pending'?'text-[#B8892D]':'text-[#8B4513]'}`}>{pair.outcome}</span></td></tr>)}</tbody></table></div><div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><Panel className="chart-panel border-4"><p className="eyebrow">Baseline comparison</p><h2 className="display-title mt-1 text-lg">Pair classification quality</h2><ResponsiveContainer width="100%" height={280}><BarChart data={performance} margin={{top:20,right:15,left:-20,bottom:0}}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="metric" tick={{fontSize:10,fontWeight:800}}/><YAxis domain={[0,1]} tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Bar dataKey="distance" name="Distance-only" fill="#D8C9A8" radius={0} isAnimationActive={false}/><Bar dataKey="text" name="Text-only" fill="#B8892D" radius={0} isAnimationActive={false}/><Bar dataKey="combined" name="Combined model" fill="#4F5B2A" radius={0} isAnimationActive={false}/></BarChart></ResponsiveContainer><div className="flex flex-wrap gap-4 text-[9px] font-black uppercase"><span>■ Distance-only</span><span className="text-[#B8892D]">■ Text-only</span><span className="text-[#4F5B2A]">■ Combined</span></div></Panel><Panel className="chart-panel border-4"><p className="eyebrow">Human review</p><h2 className="display-title mt-1 text-lg">Review outcomes</h2><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={outcome} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={78} label stroke="#2A3320" strokeWidth={2} isAnimationActive={false}>{outcome.map((_,index)=><Cell key={index} fill={palette[index+1]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer><div className="space-y-2">{outcome.map((item,index)=><p key={item.name} className="flex justify-between text-[9px] font-black uppercase"><span><i className="mr-2 inline-block h-2.5 w-2.5 border border-[#2A3320]" style={{backgroundColor:palette[index+1]}}/>{item.name}</span>{item.value}</p>)}</div></Panel></div></div>;
}

export function ProofAudit(){
  const proofs=seedIssues.filter(issue=>issue.proofSubmitted).slice(0,6);
  return <div><PageHeader eyebrow="Evaluation workspace · M5" title="Proof-of-fix audit" description="Inspect synthetic proof submissions and the signals produced by the plausibility model."/><div className="grid gap-5 lg:grid-cols-2">{proofs.map((issue,index)=><Panel key={issue.id} className="border-4"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Issue {issue.id} · Proof #{index+1}</p><h2 className="display-title mt-2 text-lg">{issue.title}</h2></div><StatusBadge status={issue.status}/></div><div className="mt-4 border-2 border-[#B8892D] bg-[#B8892D]/10 p-4"><p className="eyebrow">M5 result · Needs review</p>{[['Location match','PASS'],['Time plausibility','PASS'],['Reuse detection',index===0?'WARNING':'PASS'],['Visual change','PASS']].map(([label,value])=><div key={label} className="flex justify-between border-b border-[#E8E0D0] py-2 last:border-0"><span className="text-xs font-bold">{label}</span><span className={`text-[9px] font-black uppercase ${value==='PASS'?'text-[#4F5B2A]':'text-[#B8892D]'}`}>{value==='PASS'?'✓':'⚠'} {value}</span></div>)}</div><div className="mt-4 flex flex-wrap justify-between gap-2 text-[9px] font-black uppercase tracking-wider"><span>Confidence: {index===0?'0.73':'0.88'}</span><span>Model: M5 v0.2</span><span>Votes: {issue.verificationVotes.fixed} fixed · {issue.verificationVotes.notFixed} not fixed</span></div><Link to={`/officer/issue/${issue.id}/proof`} className="mt-4 inline-flex text-[9px] font-black uppercase tracking-wider text-[#4F5B2A] underline">View full proof →</Link></Panel>)}</div></div>;
}

export function ExperimentMetrics(){
  const matrix:Array<{name:string;[key:string]:string|number}>=categories.map((name,row)=>({name:name.split('/')[0].slice(0,7),...Object.fromEntries(categories.map((_,col)=>[String(col),row===col?78+((row*7+col*3)%18):((row*5+col*11)%19)]))}));
  const f1=[{label:'Road',f1:.86},{label:'Waste',f1:.82},{label:'Drain',f1:.79},{label:'Water',f1:.85},{label:'Light',f1:.88},{label:'Animal',f1:.74},{label:'Encroach',f1:.76},{label:'Other',f1:.78}];
  const ablation=[{name:'Full model',f1:.82,precision:.85,recall:.79},{name:'− spatial',f1:.76,precision:.8,recall:.72},{name:'− text',f1:.69,precision:.72,recall:.66},{name:'− image',f1:.73,precision:.77,recall:.7}];
  const [module,setModule]=useState('M1');
  return <div><PageHeader eyebrow="Evaluation workspace" title="Experiment metrics" description="Per-module scores and diagnostic views. All observations are illustrative and synthetic."/><div className="mb-6 flex flex-wrap gap-2">{['M1','M2','M3','M4','M5','M6'].map(name=><button key={name} onClick={()=>setModule(name)} className={`border-2 border-[#2A3320] px-4 py-2 text-[9px] font-black uppercase tracking-wider ${module===name?'bg-[#4F5B2A] text-white':'bg-[#FDFBF7]'}`}>{name}</button>)}</div><div className="mb-7 grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><Panel className="border-4"><p className="eyebrow">{module} · {module==='M1'?'Category classification':'Evaluation module'}</p><div className="mt-4 grid grid-cols-3 gap-2">{[['Macro-F1','0.82'],['Precision','0.85'],['Recall','0.79']].map(([name,value])=><div key={name} className="border-2 border-[#2A3320] bg-[#D8C9A8]/40 p-3"><p className="display-title text-2xl">{value}</p><p className="mt-1 text-[8px] font-black uppercase tracking-widest">{name}</p></div>)}</div><p className="eyebrow mt-6">Baseline comparison</p><div className="mt-3 space-y-3">{[['Keyword',.45],['TF-IDF',.68],['Ours',.82]].map(([name,value])=><div key={String(name)}><div className="mb-1 flex justify-between text-[9px] font-black uppercase"><span>{name}</span><span>{Number(value).toFixed(2)}</span></div><div className="h-3 border-2 border-[#2A3320] bg-[#E8E0D0]"><div className={`h-full ${name==='Ours'?'bg-[#4F5B2A]':name==='TF-IDF'?'bg-[#B8892D]':'bg-[#D8C9A8]'}`} style={{width:`${Number(value)*100}%`}}/></div></div>)}</div></Panel><Panel className="chart-panel border-4 min-w-0 overflow-hidden"><p className="eyebrow">8 × 8 diagnostic</p><h2 className="display-title mt-1 text-lg">Confusion matrix</h2><div className="mt-4 overflow-x-auto"><div className="grid min-w-[500px] grid-cols-[72px_repeat(8,minmax(0,1fr))] gap-1">{['',...categories.map(value=>value.split('/')[0].slice(0,4))].map((label,index)=><span key={index} className="flex items-center justify-center text-[8px] font-black uppercase">{label}</span>)}{matrix.flatMap((row,rowIndex)=>[<span key={`r-${rowIndex}`} className="flex items-center text-[8px] font-black uppercase">{row.name}</span>,...categories.map((_,colIndex)=>{const value=Number(row[String(colIndex)]);return <span key={`${rowIndex}-${colIndex}`} title={`${row.name}: ${value}%`} className="flex aspect-square items-center justify-center border border-[#2A3320]/30 text-[8px] font-bold" style={{backgroundColor:rowIndex===colIndex?`rgba(79,91,42,${.2+value/125})`:`rgba(184,137,45,${value/120})`}}>{value}</span>})])}</div></div><p className="mt-3 text-[8px] font-bold uppercase tracking-wider text-[#2A3320]/50">Predicted category → · Actual category ↓ · color intensity maps olive to gold to sand</p></Panel></div>
    <div className="mb-7 grid gap-6 xl:grid-cols-2"><ChartPanel title="Per-category F1" data={f1} dataKey="f1"/><Panel className="chart-panel border-4"><p className="eyebrow">Ablation study</p><h2 className="display-title mt-1 text-lg">Component contribution</h2><ResponsiveContainer width="100%" height={260}><BarChart data={ablation} margin={{top:15,right:6,left:-18,bottom:0}}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" tick={{fontSize:8,fontWeight:700}}/><YAxis domain={[0,1]} tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Bar dataKey="f1" name="F1" fill="#4F5B2A" radius={0} isAnimationActive={false}/><Bar dataKey="precision" name="Precision" fill="#B8892D" radius={0} isAnimationActive={false}/><Bar dataKey="recall" name="Recall" fill="#D8C9A8" radius={0} isAnimationActive={false}/></BarChart></ResponsiveContainer></Panel></div>
    <section id="dataset" className="grid gap-5 md:grid-cols-2"><Panel className="border-4"><p className="eyebrow">Dataset information</p><h2 className="display-title mt-1 text-lg">Pune civic reports · v0.3</h2><div className="mt-4 grid grid-cols-3 gap-2">{[['1,247','Records'],['70 / 15 / 15','Train / val / test'],['3','Languages']].map(([value,label])=><div key={label} className="border-2 border-[#2A3320] bg-[#D8C9A8]/35 p-3"><p className="display-title text-lg">{value}</p><p className="mt-1 text-[8px] font-black uppercase tracking-wider">{label}</p></div>)}</div><p className="mt-4 text-xs leading-relaxed text-[#2A3320]/65">Sources: synthetic civic issue narratives, service taxonomy, and coarsened Pune ward coordinates. No real citizen records are present.</p></Panel><Panel className="chart-panel border-4"><p className="eyebrow">M1 · classification</p><h2 className="display-title mt-1 text-lg">Per-language F1</h2><ResponsiveContainer width="100%" height={190}><BarChart data={[{name:'English',f1:.84},{name:'मराठी',f1:.79},{name:'हिन्दी',f1:.73}]}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" tick={{fontSize:9,fontWeight:700}}/><YAxis domain={[0,1]} tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Bar dataKey="f1" name="F1" fill="#B8892D" radius={0} isAnimationActive={false}/></BarChart></ResponsiveContainer></Panel></section></div>;
}
function ChartPanel({title,data,dataKey}:{title:string;data:Array<Record<string,string|number>>;dataKey:string}){return <Panel className="chart-panel border-4"><p className="eyebrow">M1 · classification</p><h2 className="display-title mt-1 text-lg">{title}</h2><ResponsiveContainer width="100%" height={260}><BarChart data={data}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="label" tick={{fontSize:8,fontWeight:700}}/><YAxis domain={[0,1]} tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Bar dataKey={dataKey} fill="#4F5B2A" radius={0} isAnimationActive={false}/></BarChart></ResponsiveContainer></Panel>}

export function AuditLedger(){
  const [query,setQuery]=useState('');const [actor,setActor]=useState('All');const [actionType,setActionType]=useState('All');const [fromDate,setFromDate]=useState('');const [toDate,setToDate]=useState('');const [verified,setVerified]=useState(false);
  const data=ledgerEvents.filter(event=>{const day=event.timestamp.slice(0,10);const typeMatches=actionType==='All'||(actionType==='Reported'&&event.action.startsWith('—'))||(actionType==='Reopened'&&event.action.includes('Reopened'))||(actionType==='Resolved'&&/(Claimed Resolved|Verified Fixed)/.test(event.action))||(actionType==='Status change'&&!event.action.startsWith('—'));return (actor==='All'||event.actor===actor)&&typeMatches&&(!fromDate||day>=fromDate)&&(!toDate||day<=toDate)&&`${event.issueId} ${event.action} ${event.reason}`.toLowerCase().includes(query.toLowerCase());});
  return <div><PageHeader eyebrow="Append-only integrity records" title="Audit ledger" description="Trace status changes through a hash-chained event log. Synthetic demonstration data." action={<span className="border-2 border-[#4F5B2A] bg-[#4F5B2A]/10 px-3 py-2 text-[9px] font-black uppercase tracking-wider text-[#4F5B2A]">Chain integrity · verified</span>}/><Panel className="mb-6 border-4 border-[#4F5B2A] bg-[#4F5B2A]/10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><ShieldCheck size={20}/><h2 className="display-title text-lg">Chain integrity: verified</h2></div><p className="mt-2 text-xs font-bold">Last check: 5 minutes ago · {ledgerEvents.length} total events · Chain length {ledgerEvents.length}</p>{verified&&<p className="mt-2 text-[9px] font-black uppercase tracking-widest">Integrity check passed · no broken links detected</p>}</div><Button onClick={()=>{setVerified(true);toast.success('Hash-chain integrity verified.');}}>Run integrity check</Button></div></Panel>
    <div className="mb-4 flex flex-wrap gap-3"><label className="flex items-center gap-2 border-2 border-[#2A3320] bg-[#FDFBF7] px-3 py-2"><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filter issue, action, reason" className="w-52 bg-transparent text-xs outline-none"/></label><select aria-label="Filter by actor" value={actor} onChange={event=>setActor(event.target.value)} className="border-2 border-[#2A3320] bg-[#FDFBF7] px-3 py-2 text-[9px] font-black uppercase"><option>All</option><option>Officer</option><option>Citizen</option><option>System</option></select><select aria-label="Filter by action type" value={actionType} onChange={event=>setActionType(event.target.value)} className="border-2 border-[#2A3320] bg-[#FDFBF7] px-3 py-2 text-[9px] font-black uppercase"><option>All</option><option>Reported</option><option>Status change</option><option>Resolved</option><option>Reopened</option></select><label className="flex items-center gap-2 text-[8px] font-black uppercase">From<input aria-label="From date" type="date" value={fromDate} onChange={event=>setFromDate(event.target.value)} className="border-2 border-[#2A3320] bg-[#FDFBF7] px-3 py-2 text-[9px]"/></label><label className="flex items-center gap-2 text-[8px] font-black uppercase">To<input aria-label="To date" type="date" value={toDate} onChange={event=>setToDate(event.target.value)} className="border-2 border-[#2A3320] bg-[#FDFBF7] px-3 py-2 text-[9px]"/></label></div>
    <div className="overflow-x-auto border-4 border-[#2A3320] bg-[#FDFBF7]"><table className="data-table"><thead><tr>{['Seq','Issue','Action','Actor','Timestamp','Reason','Hash'].map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{data.map(event=><tr key={event.seq}><td className="font-black">{event.seq}</td><td className="font-black">{event.issueId}</td><td>{event.action}</td><td>{event.actor}</td><td>{new Date(event.timestamp).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</td><td className="max-w-56 truncate">{event.reason}</td><td title={event.hash} className="font-mono text-[9px]">{event.hash.slice(0,12)}…</td></tr>)}</tbody></table></div>{data.length===0&&<p className="border-x-4 border-b-4 border-[#2A3320] bg-[#FDFBF7] p-6 text-center text-sm">No audit events match the current filters.</p>}</div>;
}
