import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowRight, AlertTriangle, ArrowUpRight, Building2, CalendarClock, Clock3, Eye, MapPin, ShieldCheck, Users } from 'lucide-react';
import { issues as seedIssues, scorecards, statusEvents, weeklyMetrics } from '../../data/seed';
import { loadSubmittedIssues } from '../../data/localDemo';
import type { Issue, ScorecardSnapshot } from '../../types';
import { FilterBar } from '../../components/shared/FilterBar';
import { IssueCard } from '../../components/shared/IssueCard';
import { MapView } from '../../components/shared/MapView';
import { PageHeader, Panel } from '../../components/shared/Primitives';
import { ActivityTimeline } from '../../components/shared/ActivityTimeline';
import { StatusBadge } from '../../components/shared/StatusBadge';
import { useLiveIssues } from '../../data/live';

const tip={contentStyle:{backgroundColor:'#2A3320',border:0,borderRadius:0,color:'#fff',fontSize:10},itemStyle:{color:'#fff'}};

export function PublicMap(){
  const [filter,setFilter]=useState({ward:'All',category:'All',status:'All'});const [selected,setSelected]=useState<Issue|null>(null);
  const { issues } = useLiveIssues();
  const [submittedIssues]=useState(loadSubmittedIssues);const allIssues=useMemo(()=>[...issues,...submittedIssues],[issues,submittedIssues]);
  const filtered=useMemo(()=>allIssues.filter(issue=>(filter.ward==='All'||issue.ward===filter.ward)&&(filter.category==='All'||issue.category===filter.category)&&(filter.status==='All'||issue.status===filter.status)),[filter,allIssues]);
  const metrics=[['127','Open'],['45','In progress'],['89','Resolved'],['12','Reopened']];
  return <div className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Public information · No login required" title="Public issue map — Pune" description="Privacy-coarsened locations. Explore issue status and service patterns across Pune." action={<span className="flex items-center gap-2 border-2 border-[#2A3320] bg-[#D8C9A8] px-3 py-2 text-[9px] font-black uppercase tracking-wider"><ShieldCheck size={13}/>Redacted public view</span>}/>
    <div className="mb-4 border-2 border-[#2A3320] bg-[#FDFBF7] p-3"><FilterBar filters={[{key:'ward',label:'Ward',options:['All','Ward 11','Ward 12','Ward 14','Ward 15']},{key:'category',label:'Category',options:['All','pothole/road','garbage/waste','drainage/sewage','water supply','streetlight/electrical','stray animals','encroachment','other']},{key:'status',label:'Status',options:['All','Open','Triaged','Assigned','In Progress','Claimed Resolved','Verified Fixed','Reopened']}]} onFilterChange={(key,value)=>setFilter(old=>({...old,[key]:value}))}/></div>
    <div className="relative"><MapView issues={filtered} selectedId={selected?.id} onSelectIssue={setSelected} height="min(67vh, 760px)" publicView/><div className="absolute right-3 top-3 z-[500] hidden w-40 border-4 border-[#2A3320] bg-[#FDFBF7] shadow-[4px_4px_0px_0px_#2A3320] sm:block">{metrics.map(([value,label])=><div key={label} className="flex justify-between border-b-2 border-[#E8E0D0] px-3 py-2.5 last:border-0"><span className="display-title text-xl">{value}</span><span className="self-center text-[9px] font-black uppercase tracking-wider">{label}</span></div>)}</div></div>
    <div className="mt-5 flex flex-col justify-between gap-2 border-t-2 border-[#D8C9A8] pt-4 text-[9px] font-bold uppercase tracking-wider text-[#2A3320]/55 sm:flex-row"><span>⌖ All locations are coarsened. No personal data is displayed.</span><span>Data is synthetic and shown for demonstration purposes.</span></div>{selected&&<div className="fixed inset-x-3 bottom-4 z-[600] mx-auto max-w-lg border-4 border-[#2A3320] bg-[#FDFBF7] p-4 shadow-[6px_6px_0px_0px_#2A3320]"><div className="mb-2 flex justify-between"><p className="eyebrow">Approximate issue preview</p><button onClick={()=>setSelected(null)} className="text-xs font-black">CLOSE ×</button></div><IssueCard issue={selected} variant="compact" publicView/><Link to={`/transparency/issue/${selected.id}`} className="mt-3 block text-[9px] font-black uppercase tracking-wider text-[#4F5B2A] underline">View redacted issue →</Link></div>}</div>;
}

export function Scorecards(){
  const [view,setView]=useState<'ward'|'department'>('ward');
  const grouped=useMemo(()=>{const groups=new Map<string,ScorecardSnapshot[]>();scorecards.forEach(card=>{const key=view==='ward'?card.ward:card.department;groups.set(key,[...(groups.get(key)||[]),card]);});const result:Array<{name:string;items:ScorecardSnapshot[];total:number;resolved:number;active:number;sla:number;days:string;reopen:number}>=[];groups.forEach((rows,name)=>{const n=rows.length;result.push({name,items:rows,total:rows.reduce((sum:number,row:ScorecardSnapshot)=>sum+row.totalIssues,0),resolved:rows.reduce((sum:number,row:ScorecardSnapshot)=>sum+row.resolvedIssues,0),active:rows.reduce((sum:number,row:ScorecardSnapshot)=>sum+row.activeIssues,0),sla:Math.round(rows.reduce((sum:number,row:ScorecardSnapshot)=>sum+row.slaCompliance,0)/n),days:(rows.reduce((sum:number,row:ScorecardSnapshot)=>sum+row.medianResolutionDays,0)/n).toFixed(1),reopen:Math.round(rows.reduce((sum:number,row:ScorecardSnapshot)=>sum+row.reopenRate,0)/n)});});return result;},[view]);
  const trends=weeklyMetrics;
  return <div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8 lg:py-9"><PageHeader eyebrow="Public accountability" title="Ward & department scorecards" description="System-level performance signals. No individual officers are named."/>
    <div className="mb-6 flex gap-2">{(['ward','department'] as const).map(key=><button key={key} onClick={()=>setView(key)} className={`border-2 border-[#2A3320] px-4 py-3 text-[10px] font-black uppercase tracking-wider ${view===key?'bg-[#4F5B2A] text-white shadow-[4px_4px_0px_0px_#2A3320]':'bg-[#FDFBF7]'}`}>By {key}</button>)}</div>
    <div className="mb-9 grid gap-5 md:grid-cols-2">{grouped.map((item,index)=><Panel key={item.name} className="relative border-4"><span className={`absolute right-5 top-5 h-3 w-3 ${index%3===0?'rounded-full':index%3===1?'rotate-45':''} ${['bg-[#4F5B2A]','bg-[#B8892D]','bg-[#D8C9A8]'][index%3]}`}/><div className="flex items-center gap-2">{view==='ward'?<MapPin size={17}/>:<Building2 size={17}/>}<h2 className="display-title text-xl">{item.name}</h2></div><div className="mt-5 grid grid-cols-3 border-2 border-[#2A3320] bg-[#D8C9A8]/45">{[[`${item.sla}%`,'SLA met'],[`${item.days}d`,'Median resolve'],[`${item.reopen}%`,'Reopen rate']].map(([value,label])=><div key={label} className="border-r-2 border-[#2A3320] px-3 py-3 last:border-0"><p className="display-title text-2xl">{value}</p><p className="mt-1 text-[8px] font-black uppercase tracking-widest">{label}</p></div>)}</div><div className="mt-4 flex items-center justify-between text-xs font-bold"><span>{item.active} active · {item.resolved} resolved</span><span className="text-[9px] text-[#2A3320]/50">30-day snapshot</span></div><div className="mt-4 h-20"><ResponsiveContainer width="100%" height="100%"><LineChart data={trends.slice(index,index+6)}><Line type="monotone" dataKey="days" stroke={index%2?'#B8892D':'#4F5B2A'} strokeWidth={3} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="text-[9px] font-bold uppercase tracking-wider text-[#2A3320]/45">Resolution time trend · Snapshot v1.0 · Demo data</p></Panel>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Chart title="Issues filed over time" subtitle="12-week view" type="filed"/><Chart title="Resolution time trend" subtitle="Median resolution · days" type="days"/></div><div className="mt-6"><Chart title="Category distribution" subtitle="Reports filed and resolved by week" type="area"/></div></div>;
}
function Chart({title,subtitle,type}:{title:string;subtitle:string;type:'filed'|'days'|'area'}){return <Panel className="chart-panel border-4"><div className="mb-4"><p className="eyebrow">Public trend</p><h3 className="display-title mt-1 text-lg">{title}</h3><p className="mt-1 text-[10px] text-[#2A3320]/55">{subtitle}</p></div><ResponsiveContainer width="100%" height={270}>{type==='area'?<AreaChart data={weeklyMetrics}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4"/><XAxis dataKey="week" tick={{fontSize:9,fontWeight:700}}/><YAxis tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Area dataKey="filed" name="Roads" stackId="1" stroke="#4F5B2A" fill="#4F5B2A" fillOpacity={.65} isAnimationActive={false}/><Area dataKey="resolved" name="Waste" stackId="1" stroke="#B8892D" fill="#B8892D" fillOpacity={.65} isAnimationActive={false}/></AreaChart>:type==='filed'?<LineChart data={weeklyMetrics}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4"/><XAxis dataKey="week" tick={{fontSize:9,fontWeight:700}}/><YAxis tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Line dataKey="filed" name="Filed" stroke="#4F5B2A" strokeWidth={3} dot={{r:3,fill:'#4F5B2A'}} isAnimationActive={false}/><Line dataKey="resolved" name="Resolved" stroke="#B8892D" strokeWidth={3} dot={{r:3,fill:'#B8892D'}} isAnimationActive={false}/></LineChart>:<LineChart data={weeklyMetrics}><CartesianGrid stroke="#E8E0D0" strokeDasharray="4 4"/><XAxis dataKey="week" tick={{fontSize:9,fontWeight:700}}/><YAxis tick={{fontSize:9,fontWeight:700}}/><Tooltip {...tip}/><Line dataKey="days" name="Median days" stroke="#4F5B2A" strokeWidth={3} dot={{r:3,fill:'#4F5B2A'}} isAnimationActive={false}/></LineChart>}</ResponsiveContainer></Panel>}

export function SLABreachWall(){
  const [sort,setSort]=useState('Most overdue');const [items,setItems]=useState(()=>seedIssues.filter(issue=>issue.slaBreach));
  const ordered=[...items].sort((a,b)=>sort==='Most supporters'?b.supporters-a.supporters:sort==='Newest'?a.ageInDays-b.ageInDays:(b.ageInDays-b.slaDeadlineDays)-(a.ageInDays-a.slaDeadlineDays));
  return <div className="mx-auto max-w-[1280px] px-4 pb-10 sm:px-6 lg:px-8"><section className="-mx-4 mb-7 border-b-4 border-[#2A3320] bg-[#B8892D] px-5 py-8 sm:-mx-6 sm:px-8 lg:-mx-8 lg:px-10"><p className="text-[10px] font-black uppercase tracking-[.2em]">Public accountability · Pune</p><h1 className="display-title mt-2 text-3xl md:text-4xl">SLA breach wall</h1><p className="mt-3 max-w-2xl text-sm">Issues that have exceeded their service-level deadline. No personal data. Department and ward accountability only.</p></section><div className="mb-5 flex flex-wrap items-center gap-2">{['Most overdue','Most supporters','Newest'].map(name=><button key={name} onClick={()=>setSort(name)} className={`border-2 border-[#2A3320] px-3 py-2 text-[9px] font-black uppercase tracking-wider ${sort===name?'bg-[#4F5B2A] text-white':'bg-[#FDFBF7]'}`}>{name}</button>)}</div>
    {ordered.length?<div className="grid gap-5 md:grid-cols-2">{ordered.map(issue=>{const overdue=Math.max(1,issue.ageInDays-issue.slaDeadlineDays);return <article key={issue.id} className="border-4 border-l-8 border-[#2A3320] border-l-[#B8892D] bg-[#FDFBF7] p-5 shadow-[6px_6px_0px_0px_#2A3320]"><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-[#B8892D]"><AlertTriangle size={16}/>{overdue} days overdue</p><h2 className="display-title mt-4 text-xl">{issue.title}</h2><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-[#2A3320]/60">{issue.category} · {issue.ward} · {issue.department}</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs font-bold"><span>{issue.supporters} supporters</span><span>Filed {issue.age}</span><StatusBadge status={issue.status}/></div><p className="mt-4 border-t-2 border-[#E8E0D0] pt-3 text-xs">SLA: {issue.slaDeadlineDays} days · Exceeded by <b>{overdue} days</b></p><Link to={`/transparency/issue/${issue.id}`} className="mt-4 inline-flex text-[9px] font-black uppercase tracking-widest text-[#4F5B2A] underline">View issue →</Link></article>})}</div>:<Panel className="border-4 text-center"><CheckIcon/><h2 className="display-title mt-4 text-xl">No SLA breaches currently</h2><p className="mt-2 text-sm text-[#2A3320]/60">All issues are within their service deadline.</p></Panel>}</div>;
}
function CheckIcon(){return <span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border-4 border-[#2A3320] bg-[#4F5B2A] text-xl text-white">✓</span>}

export function ForgottenIssues(){
  const list=[...seedIssues].sort((a,b)=>forgottenScore(b)-forgottenScore(a));
  return <div className="mx-auto max-w-[1280px] px-4 pb-10 sm:px-6 lg:px-8"><section className="-mx-4 mb-8 border-b-4 border-[#2A3320] bg-[#4F5B2A] px-5 py-8 text-white sm:-mx-6 sm:px-8 lg:-mx-8 lg:px-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#D8C9A8]">Public accountability · Pune</p><h1 className="display-title mt-2 text-3xl">Forgotten issues</h1><p className="mt-3 max-w-2xl text-sm text-white/80">Issues ranked by documented harm, age, and community support.</p><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-[#D8C9A8]">A prioritisation aid, not a legal ranking.</p></section><div className="space-y-4">{list.map((issue,index)=><article key={issue.id} className="grid grid-cols-[56px_1fr] gap-4 border-4 border-[#2A3320] bg-[#FDFBF7] p-4 shadow-[5px_5px_0px_0px_#2A3320] sm:grid-cols-[76px_1fr] sm:gap-6 sm:p-5"><div className="flex items-center justify-center"><div className="flex h-12 w-12 rotate-45 items-center justify-center border-2 border-[#2A3320] bg-[#4F5B2A] text-white sm:h-14 sm:w-14"><span className="-rotate-45 display-title text-lg">#{index+1}</span></div></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="eyebrow">Harm score {forgottenScore(issue).toFixed(1)} / 10</span><StatusBadge status={issue.status}/></div><h2 className="display-title mt-2 text-lg sm:text-xl">{issue.title}</h2><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-[#2A3320]/55">{issue.category} · {issue.ward} · {issue.age}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs font-medium text-[#2A3320]/70"><span>{issue.supporters} supporters</span><span>{issue.assignedOfficer?'Assigned for review':'Never assigned'}</span><span>{issue.department}</span></div><Link to={`/transparency/issue/${issue.id}`} className="mt-3 inline-flex text-[9px] font-black uppercase tracking-wider text-[#4F5B2A] underline">View issue →</Link></div></article>)}</div></div>;
}
function forgottenScore(issue:Issue){return Math.min(9.9,Math.max(1.5,issue.ageInDays*.105+issue.supporters*.105+(issue.priority===1?1.25:issue.priority===2?.6:0)));}

export function PublicIssueDetail(){
  const {id='ND-104'}=useParams();const { issues }=useLiveIssues();const issue=issues.find(item=>item.id===id)||loadSubmittedIssues().find(item=>item.id===id)||issues[0];const events=statusEvents.filter(event=>event.issueId===issue.id);
  return <div className="mx-auto max-w-5xl px-4 py-7 sm:px-6 lg:px-8"><div className="mb-5 border-4 border-[#2A3320] bg-[#D8C9A8]/40 p-4"><div className="flex items-center gap-2"><Eye size={16}/><p className="text-[10px] font-black uppercase tracking-widest">You are viewing a public, redacted view of this issue.</p></div><p className="mt-1 text-xs text-[#2A3320]/65">Reporter identity and exact coordinates are not shown.</p></div><Link to="/transparency" className="mb-5 inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-[#4F5B2A] hover:underline">← Back to public map</Link><div className="border-b-4 border-[#2A3320] pb-5"><div className="mb-3 flex flex-wrap items-center gap-3"><span className="eyebrow">{issue.category}</span><StatusBadge status={issue.status}/></div><h1 className="display-title text-2xl md:text-4xl">{issue.title}</h1><p className="mt-3 text-xs font-medium text-[#2A3320]/60">Issue {issue.id} · {issue.age} · {issue.ward} · {issue.supporters} supporters · {issue.department}</p></div><div className="mt-6 grid gap-7 md:grid-cols-[1.05fr_.95fr]"><div className="space-y-6"><section><p className="eyebrow mb-3">Approximate location</p><MapView issues={[issue]} selectedId={issue.id} height="260px" publicView/></section><section><p className="eyebrow mb-3">Public description</p><Panel className="border-4"><p className="text-sm leading-relaxed">{issue.description}</p><p className="mt-3 border-t-2 border-[#E8E0D0] pt-3 text-[9px] font-black uppercase tracking-wider text-[#2A3320]/55">Public preview · redacted derivative</p></Panel></section><Panel className="border-4 !p-0"><div className="flex h-44 items-center justify-center bg-[#D8C9A8]/40"><MapPin size={42}/></div><p className="border-t-4 border-[#2A3320] bg-[#FDFBF7] px-4 py-3 text-[9px] font-black uppercase tracking-widest">Public preview · personal data removed</p></Panel></div><div className="space-y-6"><section><p className="eyebrow mb-3">Public activity · names withheld</p><Panel className="border-4"><ActivityTimeline events={events} redacted/></Panel></section>{issue.status==='Claimed Resolved'&&<Panel className="border-4 border-[#B8892D] bg-[#B8892D]/10"><p className="display-title text-sm">Have a registered account?</p><p className="mt-2 text-xs leading-relaxed text-[#2A3320]/65">Sign in to help verify whether this claimed fix is complete.</p><Link to={`/citizen/issue/${issue.id}/verify`} className="mt-4 inline-flex text-[9px] font-black uppercase text-[#4F5B2A] underline">Login to vote →</Link></Panel>}<Panel className="border-4 bg-[#D8C9A8]/30"><p className="eyebrow">Privacy promise</p><p className="mt-2 text-xs leading-relaxed">No reporter name, exact coordinates, or original photo metadata is available in this public view.</p></Panel></div></div></div>;
}
